import random

lower = "abcdefghijklmnopqrstuwxyz"
upper = "ABCDEFGHIJKLMNOPQRSTUWXYZ"
numbers = "0123456789"
symbols = "-_@*!"

all = lower + upper + numbers + symbols
length = 16
password = "".join(random.sample(all, length))
password2 = "".join(random.sample(all, length))
password3 = "".join(random.sample(all, length))
password4 = "".join(random.sample(all, length))
password5 = "".join(random.sample(all, length))
password6 = "".join(random.sample(all, length))
password7 = "".join(random.sample(all, length))
password8 = "".join(random.sample(all, length))
password9 = "".join(random.sample(all, length))
password10 = "".join(random.sample(all, length))
password11 = "".join(random.sample(all, length))
password12 = "".join(random.sample(all, length))
password13 = "".join(random.sample(all, length))
password14 = "".join(random.sample(all, length))
password15 = "".join(random.sample(all, length))
password16 = "".join(random.sample(all, length))
password17 = "".join(random.sample(all, length))
password18 = "".join(random.sample(all, length))
password19 = "".join(random.sample(all, length))
password20 = "".join(random.sample(all, length))
password21 = "".join(random.sample(all, length))
password22 = "".join(random.sample(all, length))
password23 = "".join(random.sample(all, length))
password24 = "".join(random.sample(all, length))
password25 = "".join(random.sample(all, length))
password26 = "".join(random.sample(all, length))
password27 = "".join(random.sample(all, length))
password28 = "".join(random.sample(all, length))
password29 = "".join(random.sample(all, length))
password30 = "".join(random.sample(all, length))
password31 = "".join(random.sample(all, length))
password32 = "".join(random.sample(all, length))
password33 = "".join(random.sample(all, length))
password34 = "".join(random.sample(all, length))
password35 = "".join(random.sample(all, length))
password36 = "".join(random.sample(all, length))
password37 = "".join(random.sample(all, length))
password38 = "".join(random.sample(all, length))
password39 = "".join(random.sample(all, length))
password40 = "".join(random.sample(all, length))
password41 = "".join(random.sample(all, length))
password42 = "".join(random.sample(all, length))
password43 = "".join(random.sample(all, length))
password44 = "".join(random.sample(all, length))
password45 = "".join(random.sample(all, length))
password46 = "".join(random.sample(all, length))
password47 = "".join(random.sample(all, length))
password48 = "".join(random.sample(all, length))
password49 = "".join(random.sample(all, length))
password50 = "".join(random.sample(all, length))

print("GENERATOR PASSWORD")
print(f"1. {password}")
print(f"2. {password2}")
print(f"3. {password3}")
print(f"4. {password4}")
print(f"5. {password5}")
print(f"6. {password6}")
print(f"7. {password7}")
print(f"8. {password8}")
print(f"9. {password9}")
print(f"10. {password10}")
print(f"11. {password11}")
print(f"12. {password12}")
print(f"13. {password13}")
print(f"14. {password14}")
print(f"15. {password15}")
print(f"16. {password16}")
print(f"17. {password17}")
print(f"18. {password18}")
print(f"19. {password19}")
print(f"20. {password20}")
print(f"22. {password22}")
print(f"22. {password22}")
print(f"23. {password23}")
print(f"24. {password24}")
print(f"25. {password25}")
print(f"26. {password26}")
print(f"27. {password27}")
print(f"28. {password28}")
print(f"29. {password29}")
print(f"30. {password30}")
print(f"31. {password31}")
print(f"32. {password32}")
print(f"33. {password33}")
print(f"34. {password34}")
print(f"35. {password35}")
print(f"36. {password36}")
print(f"37. {password37}")
print(f"38. {password38}")
print(f"39. {password39}")
print(f"40. {password40}")
print(f"41. {password41}")
print(f"42. {password42}")
print(f"43. {password43}")
print(f"44. {password44}")
print(f"45. {password45}")
print(f"46. {password46}")
print(f"47. {password47}")
print(f"48. {password48}")
print(f"49. {password49}")
print(f"50. {password50}")

input()
